name: Bright

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start application
        env:
          DB_SERVER: db
          MYSQL_DATABASE: dvwa
          MYSQL_PASSWORD: p@ssw0rd
          MYSQL_ROOT_PASSWORD: dvwa
          MYSQL_USER: dvwa
        run: |
          docker compose up --wait

      - name: Probe application readiness
        run: |
          for i in {1..30}; do nc -z 127.0.0.1 4280 && exit 0 || sleep 5; done; exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install SecTesterJS dependencies
        run: |
          npm i --save=false --prefix .brightsec @sectester/core@0.47.0 @sectester/repeater@0.47.0 @sectester/scan@0.47.0 @sectester/runner@0.47.0 @sectester/reporter@0.47.0

      - name: Authenticate with Bright
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: xb19NYZ8YT1LwPoNb7q8FC
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: xb19NYZ8YT1LwPoNb7q8FC
          BRIGHT_AUTH_ID: ${{ vars.BRIGHT_AUTH_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:4280
          SECTESTER_SCAN_POOL_SIZE: ${{ vars.SECTESTER_SCAN_POOL_SIZE }}
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning --test-force-exit --test-concurrency=4 --test .brightsec/tests/*.test.ts